# Generated by Django 5.1.4 on 2024-12-23 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('surname', models.CharField(max_length=30, verbose_name='фамилия')),
                ('slug', models.SlugField(help_text='только латинские', max_length=80, unique=True, verbose_name='url')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(99)])),
                ('age2', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
