# Generated by Django 5.1.4 on 2024-12-25 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название курса')),
                ('course_id', models.CharField(max_length=20, unique=True, verbose_name='id курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('surname', models.CharField(max_length=30, verbose_name='фамилия')),
                ('slug', models.SlugField(help_text='только латинские', max_length=80, unique=True, verbose_name='url')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(99)])),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('time_update', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('course', models.ManyToManyField(blank=True, to='main.course', verbose_name='посещаемые курсы')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
                'ordering': ['surname'],
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
