# Generated by Django 5.1.4 on 2024-12-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='course',
            name='end_data',
            field=models.DateField(blank=True, null=True, verbose_name='дата конца'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_data',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='номер курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'Java Script'), ('c#', 'C Sharp')], max_length=10, verbose_name='название курса'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id', 'title')},
        ),
    ]
