# Generated by Django 5.1.4 on 2024-12-25 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_description_course_end_data_course_start_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='оценка')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата получения оценки')),
                ('date', models.DateField(verbose_name='дата')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.person', verbose_name='оценки')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
                'ordering': ['date'],
            },
        ),
    ]
