# Generated by Django 5.1.4 on 2025-01-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='main.course', verbose_name='посещаемые курсы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(help_text='только латинские', max_length=80, null=True, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=30, null=True, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='time_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='time_update',
            field=models.DateField(auto_now=True, null=True, verbose_name='дата изменения'),
        ),
    ]
