# Generated by Django 5.1.4 on 2025-01-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_person_course_alter_person_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='person',
            new_name='student',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('surname', models.CharField(max_length=30, null=True, verbose_name='фамилия')),
                ('slug', models.SlugField(help_text='только латинские', max_length=80, null=True, unique=True, verbose_name='url')),
                ('course', models.ManyToManyField(blank=True, to='main.course', verbose_name='курсы')),
            ],
            options={
                'verbose_name': 'учитель',
                'verbose_name_plural': 'учителя',
                'ordering': ['surname'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher', verbose_name='учитель'),
        ),
    ]
