# Generated by Django 5.1.4 on 2025-02-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_person_student_rename_person_grade_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='photos/user.png', null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='photos/user.png', null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
