# Generated by Django 5.1.4 on 2025-02-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_teacher_age_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
    ]
