# Generated by Django 5.1.4 on 2025-02-02 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
