# Generated by Django 5.1.4 on 2025-02-03 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_grade_options_alter_grade_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='оценка'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('surname', models.CharField(max_length=30, null=True, verbose_name='фамилия')),
                ('age', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(99)])),
                ('time_create', models.DateField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('time_update', models.DateField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('image', models.ImageField(blank=True, default='photos/user.png', null=True, upload_to='photos/%Y/%m/%d')),
                ('course', models.ManyToManyField(blank=True, to='main.course', verbose_name='посещаемые курсы')),
                ('username', models.OneToOneField(max_length=80, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name': 'пользователи',
                'verbose_name_plural': 'пользователь',
                'ordering': ['surname'],
                'unique_together': {('name', 'surname')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.person'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('person', 'course')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
