# Generated by Django 5.1.4 on 2025-02-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_teacher_course_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(default=0, max_length=7, verbose_name='права'),
        ),
    ]
