# Generated by Django 5.1.4 on 2025-02-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_person_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
    ]
