# Generated by Django 5.1.4 on 2025-02-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_person_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='persons', to='main.course', verbose_name='посещаемые курсы'),
        ),
    ]
