# Generated by Django 5.1.4 on 2025-02-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_person_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'оценка', 'verbose_name_plural': 'оценки'},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
    ]
