# Generated by Django 5.1.4 on 2025-02-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_grade_options_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='time_create',
            field=models.DateField(verbose_name='дата создания'),
        ),
    ]
